<div id="main" class="middle-east-update">
	<hr color="#999999" size="1" width="100%" />
	<h2>Intercessors International Conference<br />
	Prophecy given through Lance Lambert<br />
	Monday 3 November 1992 in Jerusalem</h2>
	<p>Hear this that I speak, says the LORD, and wait upon Me in stillness. You shall not be afraid of the turmoil that will shortly come upon all the earth, for the days of judgment have begun, and I will overthrow, and overthrow, and overthrow. I will not cease until the real spirit and character of fallen man manifests itself. I will allow My adversary, Satan, one last opportunity to challenge My authority, to challenge My word, My purpose and My Messiah.</p>
	<p>For this reason I, the LORD, will cause these political, economic, religious and physical upheavals. Do not fear all of this, for I am preparing the whole world for the last phase, for what those who do not know Me describe as a &#8220;new world order&#8221;, but which is, in fact, an old world order. It is the power and character of Babylon, energized by the spirit of darkness, the principality of Babylon. He is the spirit of antichrist, who first manifested himself at Babel seeking to produce a one-world order without Me, which attempt I foiled. But now his hour has come.</p>
	<p>Fear not, little flock of those who would enter my heart&#8217;s purposes and desires, those whom I would train to stand with Me in these stormy times of change. It is I, the Sovereign LORD, the Almighty One, who is preparing the whole world for that man of sin finally to appear. Nothing is out of My control but all is under My authority. I am behind all the shaking, all the change and upheaval, for I am preparing the whole earth, and especially Europe and America. One super power I have cast down, and another I am about to judge. I will also cast down the power of Islam, for I have seen their wickedness, says the LORD. Do not ask of Me that I will defer these judgments, for I have determined to do it and will not be deflected. Stand with Me that My will be done. Do not fear, nor be cast down by all these things. My counsel shall stand and I will perform all My pleasure; all that I have purposed for My Son shall be fulfilled and all that I have intended for those whom I have redeemed, whom I have given to My Son, shall come to pass. In the midst of all these worldwide storms, I will work worldwide by My Spirit and reap a worldwide harvest. Where darkness and suffering have been the greatest, there the harvest will be the greatest. For I, the LORD, will prepare a people for My glory. I will draw them from Russia and all the countries round about her, from China and all the countries round about her. I will draw them from the Islamic lands, multitudes and multitudes of the young. From the east and the west, from the north and the south, I will draw them. In all the turmoil and the confusion I will work mightily. With grace and with power will I anoint those who will be faithful, and with signs and with wonders will I attend their work. But those who will be faithful to Me shall suffer. Therefore allow Me, whilst there is time to work a deep work in you by My Spirit.</p>
	<p>And if My heart yearns for those whom I have redeemed from the nations, that they might be as a bride to Me and share My eternal home and glory, My heart yearns with a boundless and a surpassing love for Israel and for the Jews wherever they may be. For as I am drawing the redeemed from the corners of the earth, so will I draw My Jewish people back to the land I have given them for an eternal inheritance. I solemnly pledge that I will judge every nation, and every leader that will oppose this My purpose, and will use every means to bring them home. She, who in all her backsliding has yet carried My Name, often unknowingly, and whom My adversary has hated with a hatred as boundless as My love for her, she who has been hated, despised, afflicted and persecuted, whom the nations have cast out and trodden down under foot. I, the LORD, the Holy One of Israel, her Saviour, I the LORD will now lead her tenderly, beaten and bloodied as she is, blind and deaf as she is, I will lead her to her place as chief of the nations. Yes I the LORD declare it: those who bloodied her and hated her, shall come bowing down to the ground before her. For in all these judgments I will save her. I the LORD will do it sovereignly in the day that I cause her to cry out to Me, and will open her eyes and unlock her ears. In that day, which I will make, My heart shall sing for joy and I will dance the dance of the Bridegroom. I call you therefore to intercession that will cost you everything, that this My purpose be fulfilled. I am the Alpha and the Omega, says the LORD GOD who is and who was and who is to come, the Almighty. </p>

	<p>&nbsp;</p>

	{include file="prophetic/nav.tpl" page=2}
</div>
