<div id="main" class="middle-east-update">
	<hr color="#999999" size="1" width="100%" />
	<h2>International Intercessors Leaders&#8217; Conference<br />
	(Word from the Lord released through Lance Lambert)<br />
	Caliraya, Laguna, Philippines<br />
	Sunday 2 November 1998</h2>
	<p>My anger is stirred up, says the LORD, against the nations; for they are dividing My land and seeking to destroy My heritage. My furious anger is like a boiling cauldron against those powerful states that have produced such strategies, and who by pressure and manipulation are seeking to implement them. Now I will become their enemy, says the LORD, and I will judge them with natural disasters, by physical catastrophes, by fire, by flood, by earthquake and by eruptions. I will touch the seas, and the atmosphere, the earth and all that is within them. Moreover, I will touch them where it will hurt them the most, for I will touch their power and the foundations of their affluence and prosperity. I will smash their prosperous economies, says the LORD. They sit like potentates, so safe, so secure, believing in their own cleverness and wisdom and power; but I, the LORD, I will cause them to stumble. I will lead them into confusion and disorder. I will blind them and delude them so that they will make mistakes because they have not regarded Me, nor honoured Me; but rather they have devalued Me, deriding My word and ignoring My covenants.</p>
	<p>For too long have I been quiet, says the LORD, but now will I arise in overflowing anger and fury. In dividing My land and seeking to demoralize and destroy My people, Israel, they have thrown down the gauntlet. I, the LORD of Hosts, the Almighty One, I will take them on.</p>
	<p>Therefore, you who know Me, whom I have redeemed and saved at such cost, who seek to serve Me and to stand before Me in the place of intercession, learn to abide in Me. For all these storms and troubles will come upon both the redeemed and the unredeemed. I am your true refuge and shelter. Do not fear but trust in Me and I will be your strength. Beware of uncommanded work that you may not uncover yourselves and become casualties. For all that which I command you to do, there is grace and power and wisdom and you will be fully covered.</p>
	<p>Do not fear, says the LORD, for I am in charge and I will fulfill all My purpose. Out of this turmoil, I will bring a saved multitude beyond number from amongst the nations. And I will bring the Bride, the Wife of the Lamb, using the pressures, the afflictions and the turmoil, to purify and to refine her, if, only in a faithful remnant. And in the midst of all this shaking, in the very eye of the storm, I will save Israel. For I will open her blinded eyes and her closed mind and her locked heart and she will recognize her Messiah, her LORD and her Saviour. Tenderly and with unfailing love and I lead Israel. She who is bespattered with blood, persecuted and hated, I the LORD, the Holy One of Israel, will bring out of this turmoil, redeemed and with glory.<br />
	<br />Therefore in love, fear Me, says the LORD, your Saviour and your Deliverer, and learn to wait on Me and wait for Me. To such I will look, to those who have laid down their lives for My sake, who have humbled themselves before Me; to them will I open My heart, and reveal My mind and give understanding. For those that wait for Me shall never be confounded nor ashamed. But the self-centered, the self-serving and the self-contained, those who are proud and superior, they will be broken, says the LORD. Put your trust in Me alone. Let me be your all and you will come through this time with treasure, for I will be your eternal and unfading treasure.</p>
	<p>&nbsp;</p>

	{include file="prophetic/nav.tpl" page=3}
</div>
