<div id="main" class="middle-east-update">
	<hr color="#999999" size="1" width="100%" />
	<h2>Given at Mount Carmel, April 1986</h2>
	<p>It will not be long before there will come upon the world a time of unparalleled upheaval and turmoil. Do not fear; it is I the LORD who am shaking all things. I began this shaking with the First World War,and I greatly increased it through the Second World War. Since 1973 I have given it an even greater impetus. In the last stage, I plan to complete it with the shaking of the universe itself, with signs in sun and moon and stars. But before that point is reached I will judge the nations, and the time is near. It will not only be by war and civil war, by anarchy and terrorism, and by monetary collapses that I will judge the nations, but also by natural disasters: by earthquake, by shortages and famines, and by old and new plague diseases. I will also judge them by giving them over to their own ways, to lawlessness, to loveless selfishness, to delusion and to believing a lie; to false religion and an apostate church, even to a Christianity without Me.</p>
	<p>Do not fear when these things begin to happen, for I disclose these things to you before they commence in order that you might be prepared, and that in the day of trouble and of evil you may stand firm and overcome. For I purpose that you may become the means of encouraging and strengthening many who love Me but who are weak. I desire that through you many may become strong in Me, and that multitudes of others might find My salvation through you.</p>
	<p>And hear this! Do not fear the power of the Kremlin, nor the power of the Islamic Revolution, for I plan to break both of them through Israel. I will bring down their pride and their arrogance, and shatter them because they have blasphemed My Name. In that day I will avenge the blood of all the martyrs and of the innocent ones whom they have slaughtered. I will surely do this thing for they have thought that there was no one to judge them. But I have seen their ways and I have heard the cries of the oppressed and of the persecuted and I will break their power and make an end of them. Be therefore prepared for when all this comes to pass, to you will be given the last great opportunity to preach the gospel freely to all the nations.</p>
	<p>In the midst of all the turmoil and shaking, and at the heart of everything, is My church. In the heavenlies she is joined to Me in one Spirit, and I have destined her for the throne. You who are My beloved, whom I have redeemed and anointed - you are mine. I will equip and empower you and you will rise up and do great things in My Name, even in the midst of darkness and evil. For I will reveal My power, and My grace and My glory through you. Do not hold back nor question My ways with you, for in all My dealings with you I have always in mind that you should be part of My bride and reign with Me. Do not forget that this requires especial discipline and training. So yield to Me that I might do a work in you in the time which is left, for I plan even during all this shaking that the bride will make herself ready.</p>
	<p>And in the midst of nations on earth, seething with unrest and conflict, I have set My Israel. Yes, I say My Israel, even though they walk in disobedience and transgression, in the stubbornness of their hearts, divorced from Me through unbelief. Nevertheless, always remember that I made them enemies of the gospel for your sake. I the LORD, I Myself blinded them and hardened them that salvation might come to the gentiles in fullness. Yet they are still mine, beloved of Me with a tender and an undying love. They are My kith and My kin, and I love them. Shall I give them up for all that they have done to Me, says the LORD? Yet I have surrendered them to sorrow, to anguish of heart and to continuous suffering. But I have never given them up. In all their afflictions I was afflicted, though I neither delivered nor saved them from death. Nevertheless I have been present; I the King of Israel, I have been present, although unnoticed and unregarded, in all their sufferings. There was no gas chamber, no massacre in which I was not present. But now the time has surely come when I shall receive them, for I will reveal Myself to them and with astonishment they will recognize Me.</p>
	<p>For in the midst of these judgments multitudes upon multitudes will be saved across the nations. You will hardly know how to bring the harvest in, but My Spirit will equip you for the task. And to Israel will I also turn in that day, and I will melt the hardening which has befallen her. I will turn their blindness into clear sight and tear away the veil on their heart. Then shall they be redeemed with heart-bursting joy, and it will become a fountain of new and resurrection life to the whole company of the redeemed.</p>
	<p>Do not fear for these days, for I have purposed that you should stand with Me and serve Me in them. Fear not, for I love you and I will protect you and equip you. I, the LORD, will anoint you with a new anointing and you will work My works and fulfill My counsel. You shall stand before Me, the LORD of the whole earth, and serve Me with understanding and with power, and you shall reign with Me during these days. Above all I call you to be intercessors.</p>
	<p>&nbsp;</p>


	{include file="prophetic/nav.tpl" page=1}
</div>
